<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();

        DB::table('users')->insert([

            // =====================
            // ADMIN
            // =====================
            [
                'name' => 'Alamsyah Firdaus',
                'username' => 'alamsyahfirdaus',
                'email' => 'alamsyah.firdaus.af31@gmail.com',
                'phone' => null,
                'password' => Hash::make('123456'),
                'role' => 'admin',
                'gender' => null,
                'birth_place' => null,
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'name' => 'Admin Jaga Lansia',
                'username' => 'admin',
                'email' => 'admin@jagalansia.id',
                'phone' => null,
                'password' => Hash::make('123456'),
                'role' => 'admin',
                'gender' => null,
                'birth_place' => null,
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // =====================
            // KONSELOR
            // =====================
            [
                'name' => 'Lina Safarina',
                'username' => 'konselor',
                'email' => 'konselor@jagalansia.id',
                'phone' => null,
                'password' => Hash::make('123456'),
                'role' => 'konselor',
                'gender' => null,
                'birth_place' => null,
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // =====================
            // KONSELI
            // =====================
            [
                'name' => 'Alamsyah Firdaus',
                'username' => 'konseli',
                'email' => 'konseli@jagalansia.id',
                'phone' => null,
                'password' => Hash::make('123456'),
                'role' => 'konseli',
                'gender' => null,
                'birth_place' => null,
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // =====================
            // USER
            // =====================
            [
                'name' => 'Andi Pratama',
                'username' => 'andi.pratama',
                'email' => 'andi.pratama@mail.com',
                'phone' => '081234560001',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'gender' => null,
                'birth_place' => 'Tasikmalaya',
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Budi Santoso',
                'username' => 'budi.santoso',
                'email' => 'budi.santoso@mail.com',
                'phone' => '081234560002',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'gender' => null,
                'birth_place' => 'Bandung',
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Citra Lestari',
                'username' => 'citra.lestari',
                'email' => 'citra.lestari@mail.com',
                'phone' => '081234560003',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'gender' => null,
                'birth_place' => 'Garut',
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dedi Kurniawan',
                'username' => 'dedi.kurniawan',
                'email' => 'dedi.kurniawan@mail.com',
                'phone' => '081234560004',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'gender' => null,
                'birth_place' => 'Ciamis',
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eka Wulandari',
                'username' => 'eka.wulandari',
                'email' => 'eka.wulandari@mail.com',
                'phone' => '081234560005',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'gender' => null,
                'birth_place' => 'Banjar',
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fajar Nugraha',
                'username' => 'fajar.nugraha',
                'email' => 'fajar.nugraha@mail.com',
                'phone' => '081234560006',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'gender' => null,
                'birth_place' => 'Sumedang',
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gina Maharani',
                'username' => 'gina.maharani',
                'email' => 'gina.maharani@mail.com',
                'phone' => '081234560007',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'gender' => null,
                'birth_place' => 'Tasikmalaya',
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hendra Saputra',
                'username' => 'hendra.saputra',
                'email' => 'hendra.saputra@mail.com',
                'phone' => '081234560008',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'gender' => null,
                'birth_place' => 'Bandung',
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Indah Permata',
                'username' => 'indah.permata',
                'email' => 'indah.permata@mail.com',
                'phone' => '081234560009',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'gender' => null,
                'birth_place' => 'Garut',
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Joko Susilo',
                'username' => 'joko.susilo',
                'email' => 'joko.susilo@mail.com',
                'phone' => '081234560010',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'gender' => null,
                'birth_place' => 'Ciamis',
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kartika Dewi',
                'username' => 'kartika.dewi',
                'email' => 'kartika.dewi@mail.com',
                'phone' => '081234560011',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'gender' => null,
                'birth_place' => 'Banjar',
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lukman Hakim',
                'username' => 'lukman.hakim',
                'email' => 'lukman.hakim@mail.com',
                'phone' => '081234560012',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'gender' => null,
                'birth_place' => 'Tasikmalaya',
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maya Sari',
                'username' => 'maya.sari',
                'email' => 'maya.sari@mail.com',
                'phone' => '081234560013',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'gender' => null,
                'birth_place' => 'Bandung',
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nanda Putri',
                'username' => 'nanda.putri',
                'email' => 'nanda.putri@mail.com',
                'phone' => '081234560014',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'gender' => null,
                'birth_place' => 'Garut',
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Oki Ramadhan',
                'username' => 'oki.ramadhan',
                'email' => 'oki.ramadhan@mail.com',
                'phone' => '081234560015',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'gender' => null,
                'birth_place' => 'Ciamis',
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Putri Anggraini',
                'username' => 'putri.anggraini',
                'email' => 'putri.anggraini@mail.com',
                'phone' => '081234560016',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'gender' => null,
                'birth_place' => 'Banjar',
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rian Setiawan',
                'username' => 'rian.setiawan',
                'email' => 'rian.setiawan@mail.com',
                'phone' => '081234560017',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'gender' => null,
                'birth_place' => 'Tasikmalaya',
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Siti Aisyah',
                'username' => 'siti.aisyah',
                'email' => 'siti.aisyah@mail.com',
                'phone' => '081234560018',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'gender' => null,
                'birth_place' => 'Bandung',
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Taufik Hidayat',
                'username' => 'taufik.hidayat',
                'email' => 'taufik.hidayat@mail.com',
                'phone' => '081234560019',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'gender' => null,
                'birth_place' => 'Garut',
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yuni Rahmawati',
                'username' => 'yuni.rahmawati',
                'email' => 'yuni.rahmawati@mail.com',
                'phone' => '081234560020',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'gender' => null,
                'birth_place' => 'Tasikmalaya',
                'birth_date' => null,
                'photo' => null,
                'occupation' => null,
                'education' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}